import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { TacosComponent } from '@src/app/tacos/tacos.component';
import { FormsModule } from '@angular/forms';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';


@NgModule({
  declarations: [
    AppComponent,
    TacosComponent,
    AutoGeneratedComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
